apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_HOST: db
  DB_NAME: microservices_db
  DB_USER: postgres
  AUTH_SERVICE_URL: http://auth-service:5002
  VERIFICATION_SERVICE_URL: http://verification-service:5003
  VALIDATION_SERVICE_URL: http://validation-service:5004
  AUTHORIZATION_SERVICE_URL: http://authorization-service:5005
  BACKEND_URL: http://backend:5001
