"""
===========================================================================
 MediMatrx - VERIFICATION SERVICE
---------------------------------------------------------------------------
 Job in one sentence:
    "I decide the policy for one-time account codes - how long they last,
     how they are shaped - but I keep no copy of anybody's account. I ask
     auth-service to remember them and to check them."

 This mirrors a pattern already used elsewhere in this platform: the
 forecast service holds no copy of the optimisation algorithm and posts
 to the optimizer instead, so today's report and tomorrow's plan cannot
 drift apart. Here, verification holds no copy of user records, so a code
 confirmed by any replica of this service always agrees with the one true
 record in auth-service's database - which is also what makes this
 service safe to run at more than one replica. An in-memory cache the way
 price-service uses one would NOT be safe here: a code generated by pod A
 would be invisible to pod B, and the next request can land on either.
===========================================================================
"""

import os
import socket
import logging
import json
import random
from datetime import datetime, timedelta, timezone

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from pydantic import BaseModel

POD = os.environ.get("POD_NAME", socket.gethostname())
SERVICE = "verification"


class JsonFormatter(logging.Formatter):
    def format(self, record):
        return json.dumps({
            "ts": datetime.now(timezone.utc).isoformat(),
            "level": record.levelname.lower(),
            "service": SERVICE,
            "pod": POD,
            "message": record.getMessage(),
        })


handler = logging.StreamHandler()
handler.setFormatter(JsonFormatter())
log = logging.getLogger(SERVICE)
log.setLevel(logging.INFO)
log.handlers = [handler]
log.propagate = False

AUTH_URL = os.environ.get("AUTH_URL", "http://auth-service:8080")
INTERNAL_TOKEN = os.environ.get("INTERNAL_TOKEN", "dev-internal-token-change-me")
UPSTREAM_TIMEOUT = float(os.environ.get("UPSTREAM_TIMEOUT", "6.0"))
CODE_EXPIRY_MINUTES = int(os.environ.get("CODE_EXPIRY_MINUTES", "15"))

app = FastAPI(
    title="MediMatrx Verification Service",
    description="Issues and checks one-time account verification codes.",
    version="1.0.0",
)

_stats = {"generated": 0, "confirmed": 0, "rejected": 0}


class GenerateRequest(BaseModel):
    user_id: str


class ConfirmRequest(BaseModel):
    user_id: str
    code: str


@app.get("/healthz")
async def healthz():
    return {"status": "alive", "service": SERVICE, "pod": POD}


@app.get("/readyz")
async def readyz():
    # Stateless and dependency-free at startup: ready the instant it is up.
    return {"status": "ready", "service": SERVICE, "pod": POD, "stats": _stats}


@app.post("/api/generate", status_code=201)
async def generate(req: GenerateRequest):
    code = f"{random.randint(0, 999999):06d}"
    expires_at = datetime.now(timezone.utc) + timedelta(minutes=CODE_EXPIRY_MINUTES)

    async with httpx.AsyncClient(timeout=UPSTREAM_TIMEOUT) as client:
        try:
            resp = await client.post(
                f"{AUTH_URL}/internal/codes",
                json={"user_id": req.user_id, "code": code, "expires_at": expires_at.isoformat()},
                headers={"X-Internal-Token": INTERNAL_TOKEN},
            )
            resp.raise_for_status()
        except httpx.HTTPError as exc:
            log.error(f"could not store code for user {req.user_id}: {exc}")
            raise HTTPException(status_code=502, detail="auth-service unreachable")

    _stats["generated"] += 1
    log.info(f"generated code for user {req.user_id}")
    return {"user_id": req.user_id, "code": code, "expires_at": expires_at.isoformat()}


@app.post("/api/confirm")
async def confirm(req: ConfirmRequest):
    async with httpx.AsyncClient(timeout=UPSTREAM_TIMEOUT) as client:
        try:
            resp = await client.post(
                f"{AUTH_URL}/internal/codes/check",
                json={"user_id": req.user_id, "code": req.code},
                headers={"X-Internal-Token": INTERNAL_TOKEN},
            )
            resp.raise_for_status()
        except httpx.HTTPError as exc:
            log.error(f"could not check code for user {req.user_id}: {exc}")
            raise HTTPException(status_code=502, detail="auth-service unreachable")

    result = resp.json()
    if not result.get("valid"):
        _stats["rejected"] += 1
        raise HTTPException(status_code=400, detail=result.get("reason", "invalid code"))

    _stats["confirmed"] += 1
    log.info(f"confirmed code for user {req.user_id}")
    return {"verified": True}


@app.exception_handler(Exception)
async def unhandled(request, exc):
    log.error(f"unhandled error on {request.url.path}: {exc}")
    return JSONResponse(status_code=500, content={"error": "internal error", "pod": POD})


@app.on_event("startup")
async def startup():
    log.info(f"Verification service started. auth={AUTH_URL} ttl={CODE_EXPIRY_MINUTES}m")
